services:
  - type: web
    name: phone-tracker
    env: node
    plan: free
    rootDir: .
    buildCommand: npm install
    startCommand: npm start
    publishPath: ./public
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
